imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   pdo_mysql
#        host:     "%database_host%"
#        port:     "%database_port%"
#        dbname:   "%database_name%"
#        user:     "%database_user%"
#        password: "%database_password%"
#        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

#    orm:
#        auto_generate_proxy_classes: "%kernel.debug%"
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     localhost
                port:     '%database_port%'
                dbname:   symfony
                user:     root
                password: Dc64
                charset:  UTF8
            customer:
                driver:   pdo_mysql
                host:     ~
                port:     ~
                dbname:   DolibarrDB
                user:     ~
                password: ~
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: false

        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    AppBundle:
#                    AcmeStoreBundle: ~
#                        type:     "annotation"
                          # The directory for entity (relative to bundle path)
#                        dir:      "Entity/"
                          #the prefix
#                        prefix:   "App\Bundle\Entity\User"
            customer:
                connection: customer
                mappings:
                    AppBundle:
                        type:     "annotation"
                        dir:      "Entity/Api/"
                        prefix:   "AppBundle\Entity\Api"
#                    AcmeCustomerBundle: ~


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#fos_user
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: AppBundle\Entity\User

#easy_admin
easy_admin:
    entities:
        - AppBundle\Entity\User

#hwi_oauth
#hwi_oauth:
#    # list of names of the firewalls in which this bundle is active, this setting MUST be set
#    connect:
#        confirmation: true
#        registration_form: fos_user.registration.form
#    firewall_names: [secured_area]
#
#    fosub:
#        username_iterations: 30
#        properties:
#            github: github_id
#    resource_owners:
#        # github Access
#        github:
#            type:                github
#            client_id:           ec802b3998e11be8b92e
#            client_secret:       193a2eb94f43e2ec43b1f912e61843151a6506d2
#            scope:               "user:n.boinali@intech-so.fr,public_repo"
#            options:
#                csrf: true


#buzz_bundle
buzz:
#     listeners:
#         token: api_dolib.buzz.listener.token #mettre token
     browsers:
        dolibarr:
            client: curl
            host: http://dolibarr.localdomain/api/index.php
#            listeners: [ token ]
#            api/index.php/user/{n0}?api_key=712f3b895ada9274714a881c2859b617&id=1

twig:
    form:
        resources: ['bootstrap_3_layout.html.twig']